# Generated by Django 3.2.25 on 2024-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
