# Generated by Django 3.2.25 on 2024-07-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_reviewer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer_image',
        ),
    ]
